### ISSUE TITLE
Run on GitHub pages

### ISSUE THREAD

**Issue by grokify** [tylerlong/ringcentral-token-generator#1]
Since this is JS, can we host and run this on GitHub pages so nothing needs to be installed?

If it's not possible, can we run online, say on Heroku?

**Comment by tylerlong** [comment]
GitHub pages is not possible because it is not all client side. For example, it starts a ngrok process in the background.

Running it on Heroku is possible.

**Comment by tylerlong** [comment]
Update: running it on Heroku is impossible.

Because when the user click "Add to Glip" button. It's **server-to-server** communication between RC and Heroku, nothing is being sent to user's browser.
